Extend validation function
danielhuppmann/nomenclature pull request #1
Opened 2020-08-03 10:37 UTC by sebastianzwickl

Add functionalities related to sub-annual and time column

2020-08-17 15:33 UTC, danielhuppmann commented on nomenclature/__init__.py
> +    elif 'time' in df.data.columns:
What is this line supposed to do? Running the following snippet does not yield a useful error/warning message...

```
TEST_DF = pd.DataFrame([
    ['model_a', 'scen_a', 'EU27', 'Primary Energy', 'EJ/yr', 1, 6.],
    ['model_a', 'scen_a', 'EU27', 'Primary Energy|Coal', 'EJ/yr', 0.5, 3],
    ['model_a', 'scen_b', 'EU27', 'Primary Energy', 'EJ/yr', 2, 7],
],
    columns=pyam.IAMC_IDX + ['2005-06-17 00:00:00', '2010-07-21 12:00:00'],
)

df = pyam.IamDataFrame(TEST_DF)
nomenclature.validate(df)
```

2020-08-21 08:58 UTC, sebastianzwickl commented on nomenclature/__init__.py
> +    elif 'time' in df.data.columns:
Yes, thank you for your advice.

2020-08-21 08:59 UTC, sebastianzwickl commented on nomenclature/tests/test_transform_functionality.py
> +import pandas as pd
Yes, thank you for your advice.

2020-08-24 07:44 UTC, sebastianzwickl commented on nomenclature/__init__.py
> +    elif 'time' in df.data.columns:
Thank you, this command line only makes sense if function `time_to_year_subannual` is used. I will fix this.

2020-08-25 12:38 UTC, danielhuppmann commented on nomenclature/__init__.py
> +def validate_time_dt(x):
suggest to rename to "internal" function by adding `_`
```suggestion
def _validate_time_dt(x):
```

2020-08-25 12:39 UTC, danielhuppmann commented on nomenclature/__init__.py
> +
remove empty lines at end of file
```suggestion 
```

2020-08-25 12:42 UTC, danielhuppmann commented on nomenclature/__init__.py
> +        valid, bool, invalid = validate_time_dt(df.data.time)
naming a variable `bool` is not helpful...

2020-08-25 14:05 UTC, sebastianzwickl commented on nomenclature/__init__.py
> +        valid, bool, invalid = validate_time_dt(df.data.time)
That seems to be no information and bad karma - thank you. I will rename it.

2020-08-26 11:23 UTC, danielhuppmann requested changes
Thanks @sebastianzwickl but you were a bit too quick to merge https://github.com/sebastianzwickl/nomenclature/pull/6, I was still in the process of writing more review comments... Now inserted here.

2020-08-26 11:23 UTC, danielhuppmann commented on nomenclature/__init__.py
> +            string = ''.join(s.rsplit(':', 1))
why is this split-and-join necessary - seems it wasn't required in the previous implementation (`datetime.strptime(f'{y}-{s}'`)? If necessary (or beneficial), please add a comment.

2020-08-26 11:23 UTC, danielhuppmann commented on nomenclature/__init__.py
> +    return invalid_dt, passed
The intention of the workflow was as follows:
1. check if the entries in `subannual` column are in the `subannual` dictionary (in the main function)
2. any "invalid" entries are passed to the `_validate_subannual_dt` function
a. check if conforms to expected format (with timezone)
b. if fails, check for conforming to `datetime` but without timezone, write error message about wrong timezone
c. if also fails, return to main function as `invalid` to be printed with the "not defined in the nomenclature" warning

The new implementation returns a "not defined in the nomenclature" warning for a subannual-value of `01-01 00:00` where "missing timezone" would be a more appropriate warning message.

2020-08-26 11:23 UTC, danielhuppmann commented on nomenclature/__init__.py
> +    valid_dt, invalid_dt, passed = [], set(), True
for consistency with the main function, calling this variable `success` would be better

2020-08-26 11:32 UTC, danielhuppmann commented on nomenclature/tests/test_castable_functionality.py
> +import pandas as pd
Note that the tests in this file are not actually related to the casting-feature - so it might be more appropriate to move them to `test_validate.py`

2020-08-26 11:33 UTC, danielhuppmann commented on nomenclature/tests/test_transform_functionality.py
> +    print(obs_year)
please remove the print statements

2020-08-26 12:26 UTC, sebastianzwickl commented on nomenclature/__init__.py
> +            string = ''.join(s.rsplit(':', 1))
Data in the `subannual `column is delivered in the following form `01-01 00:00+01:00`. 
Data from the `time` column is transformed to `2015-01-01 00:00+0100` as `%z` represents the time zone as `+HHMM`. Therefore the last `:` needs to be replaced.

2020-08-26 12:40 UTC, sebastianzwickl commented on nomenclature/tests/test_castable_functionality.py
> +import pandas as pd
Yes. Thank you - I will move them into `test_validate.py`

2020-08-26 12:48 UTC, danielhuppmann commented on nomenclature/__init__.py
> +            string = ''.join(s.rsplit(':', 1))
It seems to me that writing the timezone either as `+0100` or `+01:00` work fine in Python (and are seen as equivalent):
```
datetime.strptime('2010-01-17 00:00+0100', '%Y-%m-%d %H:%M%z')
datetime.strptime('2010-01-17 00:00+01:00', '%Y-%m-%d %H:%M%z')
```

2020-08-26 13:27 UTC, sebastianzwickl commented on nomenclature/__init__.py
> +            string = ''.join(s.rsplit(':', 1))
I fixed errors with the `join` command while testing. However, now both work for me. I will delete the command line.

2020-08-26 14:29 UTC, sebastianzwickl commented on nomenclature/__init__.py
> +    return invalid_dt, passed
I see. I will add these functionalities to the PR.

2020-08-27 12:24 UTC, danielhuppmann requested changes
one last comment...

2020-08-27 12:24 UTC, danielhuppmann commented on nomenclature/__init__.py
> +
This line is a repetition because the entries are already checked against the `codelist` (for every column) at line 120
```suggestion
```

2020-08-27 12:33 UTC, sebastianzwickl commented
> one last comment...

It's like Hilbert's Hotel ;) 
I thank you for your review.

2020-08-27 13:06 UTC, danielhuppmann approved these changes
thanks @sebastianzwickl for the additional validation features!

2020-08-27 13:07 UTC, merged